name: flutter_cast_video_example
description: Demonstrates how to use the flutter_cast_video plugin.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=3.0.0 <3.3.0"


dependencies:
  flutter:
    sdk: flutter

  flutter_cast_video:
    path: ../


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

