name: flutter_cast_video
description: flutter_cast_video let you discover cast devices like Chrome Cast and Apple TV and connect to them.
version: 1.3.0
homepage: https://github.com/whowillcare/flutter_cast_video

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  stream_transform:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: it.aesys.flutter_cast_video
        pluginClass: FlutterVideoCastPlugin
      ios:
        pluginClass: FlutterVideoCastPlugin
